import { addDays, subDays, format } from 'date-fns';

const today = new Date();

// ── Demo Business ──────────────────────────────────────────
export const DEMO_BUSINESS = {
  id: 'demo-001',
  business_name: 'Spice Garden Restaurant',
  business_type: 'restaurant',
  owner_name: 'Rajesh Kumar',
  phone: '+91 98765 43210',
  email: 'rajesh@spicegarden.in',
  address: '12, Link Road, Andheri West',
  cities: ['Mumbai, Maharashtra'],
  // Backward-compat fields (UI still reads these during migration)
  city: 'Mumbai',
  state: 'Maharashtra',
  country: 'India',
};

// ── Demo Requirements (master permit catalog) ──────────────
export const DEMO_REQUIREMENTS = [
  {
    id: 'demo-req-001',
    business_type: 'restaurant',
    city: 'Mumbai, Maharashtra',
    jurisdiction_level: 'federal',
    requirement_name: 'FSSAI Food License',
    legacy_type_id: 'FSSAI',
    issuing_agency: 'Food Safety and Standards Authority of India',
    fee_min: 2000,
    fee_max: 5000,
    renewal_cycle_months: 12,
    processing_time: '7-14 business days',
    description: 'Mandatory food safety license for any food business in India.',
    source_url: 'https://foscos.fssai.gov.in',
  },
  {
    id: 'demo-req-002',
    business_type: 'restaurant',
    city: 'Mumbai, Maharashtra',
    jurisdiction_level: 'state',
    requirement_name: 'Fire NOC',
    legacy_type_id: 'FIRE_NOC',
    issuing_agency: 'Maharashtra Fire & Emergency Services',
    fee_min: 1000,
    fee_max: 10000,
    renewal_cycle_months: 12,
    processing_time: '14-30 business days',
    description: 'No Objection Certificate from fire department for fire safety compliance.',
    source_url: 'https://mumbaimunicipal.gov.in',
  },
  {
    id: 'demo-req-003',
    business_type: 'restaurant',
    city: 'Mumbai, Maharashtra',
    jurisdiction_level: 'city',
    requirement_name: 'Trade License',
    legacy_type_id: 'TRADE_LICENSE',
    issuing_agency: 'BMC (Brihatmumbai Municipal Corporation)',
    fee_min: 5000,
    fee_max: 25000,
    renewal_cycle_months: 12,
    processing_time: '7-21 business days',
    description: 'Municipal trade license permitting commercial business operations.',
    source_url: 'https://portal.mcgm.gov.in',
  },
  {
    id: 'demo-req-004',
    business_type: 'restaurant',
    city: 'Mumbai, Maharashtra',
    jurisdiction_level: 'state',
    requirement_name: 'Shop & Establishment Registration',
    legacy_type_id: 'SHOP_ESTABLISHMENT',
    issuing_agency: 'Maharashtra Labour Department',
    fee_min: 500,
    fee_max: 2000,
    renewal_cycle_months: 12,
    processing_time: '7-14 business days',
    description: 'Registration under the Shops and Establishments Act.',
    source_url: 'https://mahashramm.gov.in',
  },
  {
    id: 'demo-req-005',
    business_type: 'restaurant',
    city: 'Mumbai, Maharashtra',
    jurisdiction_level: 'federal',
    requirement_name: 'GST Registration',
    legacy_type_id: 'GST',
    issuing_agency: 'GST Council of India',
    fee_min: 0,
    fee_max: 0,
    renewal_cycle_months: null,
    processing_time: '3-7 business days',
    description: 'Goods and Services Tax registration.',
    source_url: 'https://www.gst.gov.in',
  },
  {
    id: 'demo-req-006',
    business_type: 'restaurant',
    city: 'Mumbai, Maharashtra',
    jurisdiction_level: 'city',
    requirement_name: 'Eating House License',
    legacy_type_id: 'EATING_HOUSE',
    issuing_agency: 'Mumbai City Police',
    fee_min: 2000,
    fee_max: 5000,
    renewal_cycle_months: 12,
    processing_time: '21-45 business days',
    description: 'Police license required for any establishment serving food and beverages.',
    source_url: 'https://mumbaipolice.gov.in',
  },
  // Federal — Reusable across all cities for Food Truck
  {
    id: 'demo-req-ein',
    business_type: 'food_truck',
    city: 'Federal / All Cities',
    jurisdiction_level: 'federal',
    requirement_name: 'Employer Identification Number (EIN)',
    legacy_type_id: 'BUSINESS_LICENSE',
    issuing_agency: 'IRS (Internal Revenue Service)',
    fee_min: 0,
    fee_max: 0,
    renewal_cycle_months: null,
    processing_time: 'Instant online',
    description: 'Federal Tax Identification Number issued by the Internal Revenue Service for business tax reporting and hiring employees.',
    source_url: 'https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online',
  },
  // New York, NY — Food Truck
  {
    id: 'demo-req-nyc-1',
    business_type: 'food_truck',
    city: 'New York, NY',
    jurisdiction_level: 'city',
    requirement_name: 'Mobile Food Vending License',
    legacy_type_id: 'BUSINESS_LICENSE',
    issuing_agency: 'DCWP (NYC Dept. of Consumer & Worker Protection)',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: 24,
    processing_time: '14-30 business days',
    description: 'Personal license authorizing an individual to vend food from a mobile food unit in NYC public space.',
    source_url: 'https://nyc-business.nyc.gov/nycbusiness/description/mobile-food-vending-license',
    template_url: 'https://www.nyc.gov/assets/doh/downloads/pdf/sbs/314c-standard-form.pdf',
    form_field_map: {
      mode: 'overlay',
      fields: {
        business_name: { page: 0, x: 140, y: 665, fontSize: 10 },
        owner_name: { page: 0, x: 140, y: 635, fontSize: 10 },
        phone: { page: 0, x: 420, y: 635, fontSize: 10 },
        email: { page: 0, x: 140, y: 610, fontSize: 10 },
        address: { page: 0, x: 140, y: 585, fontSize: 10 },
        city: { page: 0, x: 420, y: 585, fontSize: 10 },
        business_type: { page: 0, x: 140, y: 555, fontSize: 10 },
        date: { page: 0, x: 450, y: 710, fontSize: 10 }
      }
    }
  },
  {
    id: 'demo-req-nyc-2',
    business_type: 'food_truck',
    city: 'New York, NY',
    jurisdiction_level: 'city',
    requirement_name: 'Mobile Food Vendor (MFV) Permit',
    legacy_type_id: 'HEALTH_PERMIT',
    issuing_agency: 'DOHMH (NYC Dept. of Health & Mental Hygiene)',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: 24,
    processing_time: '30-60 business days',
    description: 'Permit authorizing the operation of a specific mobile food vending truck or pushcart unit.',
    source_url: 'https://www.nyc.gov/site/doh/business/food-operators/mobile-and-temporary-food-vendors.page',
    template_url: 'https://www.nyc.gov/assets/doh/downloads/pdf/sbs/314c-standard-form.pdf',
    form_field_map: {
      mode: 'overlay',
      fields: {
        business_name: { page: 0, x: 140, y: 665, fontSize: 10 },
        owner_name: { page: 0, x: 140, y: 635, fontSize: 10 },
        phone: { page: 0, x: 420, y: 635, fontSize: 10 },
        email: { page: 0, x: 140, y: 610, fontSize: 10 },
        address: { page: 0, x: 140, y: 585, fontSize: 10 },
        city: { page: 0, x: 420, y: 585, fontSize: 10 },
        business_type: { page: 0, x: 140, y: 555, fontSize: 10 },
        date: { page: 0, x: 450, y: 710, fontSize: 10 }
      }
    }
  },
  {
    id: 'demo-req-nyc-3',
    business_type: 'food_truck',
    city: 'New York, NY',
    jurisdiction_level: 'city',
    requirement_name: 'Mobile Food Vendor Food Protection Certificate',
    legacy_type_id: 'HEALTH_PERMIT',
    issuing_agency: 'DOHMH (NYC Dept. of Health & Mental Hygiene)',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: null,
    processing_time: '1-3 business days',
    description: 'Mandatory food protection and safety manager certificate for supervisors of mobile food vending operations.',
    source_url: 'https://www.nyc.gov/site/doh/business/food-operators/mobile-and-temporary-food-vendors.page',
    template_url: 'https://www.nyc.gov/assets/doh/downloads/pdf/sbs/314c-standard-form.pdf',
    form_field_map: {
      mode: 'overlay',
      fields: {
        business_name: { page: 0, x: 140, y: 665, fontSize: 10 },
        owner_name: { page: 0, x: 140, y: 635, fontSize: 10 },
        phone: { page: 0, x: 420, y: 635, fontSize: 10 },
        email: { page: 0, x: 140, y: 610, fontSize: 10 },
        address: { page: 0, x: 140, y: 585, fontSize: 10 },
        city: { page: 0, x: 420, y: 585, fontSize: 10 },
        business_type: { page: 0, x: 140, y: 555, fontSize: 10 },
        date: { page: 0, x: 450, y: 710, fontSize: 10 }
      }
    }
  },
  {
    id: 'demo-req-nyc-4',
    business_type: 'food_truck',
    city: 'New York, NY',
    jurisdiction_level: 'state',
    requirement_name: 'NYS Certificate of Authority (Sales Tax)',
    legacy_type_id: 'SALES_TAX',
    issuing_agency: 'NY State Dept. of Taxation & Finance',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: null,
    processing_time: '5-10 business days',
    description: 'State certificate authorizing collection of sales tax on retail food and beverage sales in New York.',
    source_url: 'https://www.tax.ny.gov',
  },
  {
    id: 'demo-req-nyc-5',
    business_type: 'food_truck',
    city: 'New York, NY',
    jurisdiction_level: 'city',
    requirement_name: 'Environmental Control Board (ECB) Clearance',
    legacy_type_id: 'BUSINESS_LICENSE',
    issuing_agency: 'NYC ECB / OATH',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: 12,
    processing_time: '1-5 business days',
    description: 'Clearance certificate confirming all outstanding NYC ECB vendor notices and violations are cleared.',
    source_url: 'https://nyc-business.nyc.gov/nycbusiness/description/mobile-food-vending-license',
  },
  {
    id: 'demo-req-nyc-6',
    business_type: 'food_truck',
    city: 'New York, NY',
    jurisdiction_level: 'city',
    requirement_name: 'Commissary Agreement',
    legacy_type_id: 'HEALTH_PERMIT',
    issuing_agency: 'DOHMH Requirement',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: 12,
    processing_time: '1-7 business days',
    description: 'Official written agreement with a licensed commercial kitchen/commissary for daily servicing and food storage.',
    source_url: 'https://nyc-business.nyc.gov/nycbusiness/description/mobile-food-vending-unit-permit-full-term',
    template_url: 'https://www.nyc.gov/assets/doh/downloads/pdf/sbs/314c-standard-form.pdf',
    form_field_map: {
      mode: 'overlay',
      fields: {
        business_name: { page: 0, x: 140, y: 665, fontSize: 10 },
        owner_name: { page: 0, x: 140, y: 635, fontSize: 10 },
        phone: { page: 0, x: 420, y: 635, fontSize: 10 },
        email: { page: 0, x: 140, y: 610, fontSize: 10 },
        address: { page: 0, x: 140, y: 585, fontSize: 10 },
        city: { page: 0, x: 420, y: 585, fontSize: 10 },
        business_type: { page: 0, x: 140, y: 555, fontSize: 10 },
        date: { page: 0, x: 450, y: 710, fontSize: 10 }
      }
    }
  },
  // Los Angeles, CA — Food Truck
  {
    id: 'demo-req-la-1',
    business_type: 'food_truck',
    city: 'Los Angeles, CA',
    jurisdiction_level: 'city',
    requirement_name: 'LA County Mobile Food Facility (MFF) Permit',
    legacy_type_id: 'HEALTH_PERMIT',
    issuing_agency: 'LACDPH (LA County Dept. of Public Health)',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: 12,
    processing_time: '14-30 business days',
    description: 'Public health permit authorizing mobile food facility operations within LA County jurisdictions.',
    source_url: 'https://ftala.org/Permits-and-Licenses-2025',
    template_url: 'http://publichealth.lacounty.gov/eh/docs/permit/Public-Health-Permit-License-Application.pdf',
    form_field_map: {
      mode: 'acroform',
      fields: {
        'LEGAL NAME OF BUSINESS DBA': 'business_name',
        'Business Street AddressRow1': 'address',
        'CityRow1': 'city',
        'ZipRow1': 'zip',
        'OWNER 1': 'owner_name',
        'PhoneOWNER 1': 'phone',
        'EmailOWNER 1': 'email',
        'Print Name Title': 'owner_name',
        'Date of Application': 'date',
        'Signature Date': 'date',
        'Mobile Food Facility': 'checkbox_true',
        'New Business': 'checkbox_true'
      }
    }
  },
  {
    id: 'demo-req-la-2',
    business_type: 'food_truck',
    city: 'Los Angeles, CA',
    jurisdiction_level: 'city',
    requirement_name: 'City of LA Business Tax Registration Certificate (BTRC)',
    legacy_type_id: 'BUSINESS_LICENSE',
    issuing_agency: 'City of LA Office of Finance',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: 12,
    processing_time: '3-7 business days',
    description: 'Mandatory municipal tax registration for doing business within the City of Los Angeles limits.',
    source_url: 'https://streetlegal.io/blog/california/los-angeles-food-truck-permit-guide',
  },
  {
    id: 'demo-req-la-3',
    business_type: 'food_truck',
    city: 'Los Angeles, CA',
    jurisdiction_level: 'state',
    requirement_name: 'California Seller\'s Permit',
    legacy_type_id: 'SALES_TAX',
    issuing_agency: 'CDTFA (California Dept. of Tax & Fee Administration)',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: null,
    processing_time: '1-5 business days',
    description: 'State sales tax permit required for retail sales of food and goods within California.',
    source_url: 'https://streetlegal.io/blog/california/los-angeles-food-truck-permit-guide',
  },
  {
    id: 'demo-req-la-4',
    business_type: 'food_truck',
    city: 'Los Angeles, CA',
    jurisdiction_level: 'city',
    requirement_name: 'Commissary Letter of Agreement',
    legacy_type_id: 'HEALTH_PERMIT',
    issuing_agency: 'LACDPH Requirement',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: 12,
    processing_time: '1-7 business days',
    description: 'Formally executed agreement with an approved commercial commissary facility for cleaning, filling, and storage.',
    source_url: 'https://streetlegal.io/blog/california/los-angeles-food-truck-permit-guide',
    template_url: 'http://publichealth.lacounty.gov/eh/docs/permit/Public-Health-Permit-License-Application.pdf',
    form_field_map: {
      mode: 'acroform',
      fields: {
        'LEGAL NAME OF BUSINESS DBA': 'business_name',
        'Business Street AddressRow1': 'address',
        'CityRow1': 'city',
        'ZipRow1': 'zip',
        'OWNER 1': 'owner_name',
        'PhoneOWNER 1': 'phone',
        'EmailOWNER 1': 'email',
        'Print Name Title': 'owner_name',
        'Date of Application': 'date',
        'Signature Date': 'date',
        'Mobile Food Facility': 'checkbox_true',
        'New Business': 'checkbox_true'
      }
    }
  },
  {
    id: 'demo-req-la-5',
    business_type: 'food_truck',
    city: 'Los Angeles, CA',
    jurisdiction_level: 'state',
    requirement_name: 'California Food Handler Card',
    legacy_type_id: 'HEALTH_PERMIT',
    issuing_agency: 'CA Dept. of Public Health',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: 36,
    processing_time: '1-2 business days',
    description: 'State-mandated food handler training certificate for food service workers in food facility operations.',
    source_url: 'https://getvendorloop.com/guides/how-to-start-a-food-truck-in-los-angeles',
  },
  {
    id: 'demo-req-la-6',
    business_type: 'food_truck',
    city: 'Los Angeles, CA',
    jurisdiction_level: 'city',
    requirement_name: 'Food Protection Manager Certification',
    legacy_type_id: 'HEALTH_PERMIT',
    issuing_agency: 'LACDPH',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: 60,
    processing_time: '1-5 business days',
    description: 'Certified food safety manager accreditation required for person-in-charge of mobile food facilities.',
    source_url: 'https://getvendorloop.com/guides/how-to-start-a-food-truck-in-los-angeles',
    template_url: 'http://publichealth.lacounty.gov/eh/docs/permit/Public-Health-Permit-License-Application.pdf',
    form_field_map: {
      mode: 'acroform',
      fields: {
        'LEGAL NAME OF BUSINESS DBA': 'business_name',
        'Business Street AddressRow1': 'address',
        'CityRow1': 'city',
        'ZipRow1': 'zip',
        'OWNER 1': 'owner_name',
        'PhoneOWNER 1': 'phone',
        'EmailOWNER 1': 'email',
        'Print Name Title': 'owner_name',
        'Date of Application': 'date',
        'Signature Date': 'date',
        'Mobile Food Facility': 'checkbox_true',
        'New Business': 'checkbox_true'
      }
    }
  },
  {
    id: 'demo-req-la-7',
    business_type: 'food_truck',
    city: 'Los Angeles, CA',
    jurisdiction_level: 'state',
    requirement_name: 'HCD Insignia (Vehicle Inspection)',
    legacy_type_id: 'FIRE_PERMIT',
    issuing_agency: 'CA Dept. of Housing & Community Development',
    fee_min: null,
    fee_max: null,
    fee_note: 'estimate — verify against official agency fee schedule before demo',
    renewal_cycle_months: null,
    processing_time: '14-30 business days',
    description: 'State safety certification insignia for commercial mobile food trucks and trailers with electrical or gas systems.',
    source_url: 'https://runpitstop.com/blog/food-truck-permits-california',
  },
];

// ── Demo Business Requirements (per-business checklist) ────
export const DEMO_BUSINESS_REQUIREMENTS = [
  {
    id: 'demo-br-001',
    business_id: 'demo-001',
    requirement_id: 'demo-req-001',
    status: 'expired',
    license_number: 'FSSAI-2021-MH-0049821',
    issuing_authority: 'Food Safety and Standards Authority of India',
    document_url: null,
    expiry_date: format(subDays(today, 12), 'yyyy-MM-dd'),
    extracted_via_ocr: true,
    // Joined fields from requirement (for UI convenience)
    requirement: DEMO_REQUIREMENTS[0],
  },
  {
    id: 'demo-br-002',
    business_id: 'demo-001',
    requirement_id: 'demo-req-002',
    status: 'in_progress',
    license_number: 'MFB/MUM/2023/00441',
    issuing_authority: 'Maharashtra Fire & Emergency Services',
    document_url: null,
    expiry_date: format(addDays(today, 8), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS[1],
  },
  {
    id: 'demo-br-003',
    business_id: 'demo-001',
    requirement_id: 'demo-req-003',
    status: 'in_progress',
    license_number: 'BMC/TL/AND/2023/88321',
    issuing_authority: 'BMC (Brihatmumbai Municipal Corporation)',
    document_url: null,
    expiry_date: format(addDays(today, 23), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS[2],
  },
  {
    id: 'demo-br-004',
    business_id: 'demo-001',
    requirement_id: 'demo-req-004',
    status: 'in_progress',
    license_number: 'MH-LAB/SE/2023/40129',
    issuing_authority: 'Maharashtra Labour Department',
    document_url: null,
    expiry_date: format(addDays(today, 52), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS[3],
  },
  {
    id: 'demo-br-005',
    business_id: 'demo-001',
    requirement_id: 'demo-req-005',
    status: 'satisfied',
    license_number: '27AABCS1429B1Z1',
    issuing_authority: 'GST Council of India',
    document_url: null,
    expiry_date: format(addDays(today, 240), 'yyyy-MM-dd'),
    extracted_via_ocr: true,
    requirement: DEMO_REQUIREMENTS[4],
  },
  {
    id: 'demo-br-006',
    business_id: 'demo-001',
    requirement_id: 'demo-req-006',
    status: 'satisfied',
    license_number: 'MP/EH/AND/2023/11042',
    issuing_authority: 'Mumbai City Police',
    document_url: null,
    expiry_date: format(addDays(today, 180), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS[5],
  },
];

// ── Additional Demo Business Profiles ──────────────────────
export const DEMO_BUSINESS_RICO = {
  id: 'demo-rico-001',
  business_name: "Rico's Curbside Kitchen",
  business_type: 'food_truck',
  owner_name: 'Mara Delgado',
  phone: '+1 212 555 0199',
  email: 'mara@ricoscurbside.com',
  address: '450 W 42nd St, New York, NY',
  cities: ['New York, NY'],
  city: 'New York',
  state: 'NY',
  country: 'USA',
};

export const DEMO_BUSINESS_GRANDVIEW = {
  id: 'demo-grandview-002',
  business_name: 'Grandview Grill Co.',
  business_type: 'food_truck',
  owner_name: 'Owen Castillo',
  phone: '+1 212 555 0188',
  email: 'owen@grandviewgrill.com',
  address: '100 Grandview Ave, New York, NY',
  cities: ['New York, NY'],
  city: 'New York',
  state: 'NY',
  country: 'USA',
};

export const DEMO_BUSINESS_REQUIREMENTS_RICO = [
  {
    id: 'rico-br-001',
    business_id: 'demo-rico-001',
    requirement_id: 'demo-req-nyc-3',
    status: 'satisfied',
    license_number: 'NYC-DOHMH-FPC-88912',
    issuing_authority: 'DOHMH (NYC Dept. of Health & Mental Hygiene)',
    document_url: null,
    expiry_date: format(addDays(today, 180), 'yyyy-MM-dd'),
    extracted_via_ocr: true,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-3'),
  },
  {
    id: 'rico-br-002',
    business_id: 'demo-rico-001',
    requirement_id: 'demo-req-ein',
    status: 'satisfied',
    license_number: 'EIN-12-3456789',
    issuing_authority: 'IRS (Internal Revenue Service)',
    document_url: null,
    expiry_date: format(addDays(today, 365), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-ein'),
  },
  {
    id: 'rico-br-003',
    business_id: 'demo-rico-001',
    requirement_id: 'demo-req-nyc-1',
    status: 'needed',
    license_number: null,
    issuing_authority: 'DCWP (NYC Dept. of Consumer & Worker Protection)',
    document_url: null,
    expiry_date: null,
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-1'),
  },
  {
    id: 'rico-br-004',
    business_id: 'demo-rico-001',
    requirement_id: 'demo-req-nyc-2',
    status: 'needed',
    license_number: null,
    issuing_authority: 'DOHMH (NYC Dept. of Health & Mental Hygiene)',
    document_url: null,
    expiry_date: null,
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-2'),
  },
  {
    id: 'rico-br-005',
    business_id: 'demo-rico-001',
    requirement_id: 'demo-req-nyc-6',
    status: 'needed',
    license_number: null,
    issuing_authority: 'DOHMH Requirement',
    document_url: null,
    expiry_date: null,
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-6'),
  },
  {
    id: 'rico-br-006',
    business_id: 'demo-rico-001',
    requirement_id: 'demo-req-nyc-4',
    status: 'in_progress',
    license_number: 'NYS-TAX-994821',
    issuing_authority: 'NY State Dept. of Taxation & Finance',
    document_url: null,
    expiry_date: format(addDays(today, 20), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-4'),
  },
  {
    id: 'rico-br-007',
    business_id: 'demo-rico-001',
    requirement_id: 'demo-req-nyc-5',
    status: 'expired',
    license_number: 'ECB-VIOL-2023-441',
    issuing_authority: 'NYC ECB / OATH',
    document_url: null,
    expiry_date: format(subDays(today, 60), 'yyyy-MM-dd'),
    extracted_via_ocr: true,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-5'),
  },
];

export const DEMO_BUSINESS_REQUIREMENTS_GRANDVIEW = [
  {
    id: 'grand-br-001',
    business_id: 'demo-grandview-002',
    requirement_id: 'demo-req-ein',
    status: 'satisfied',
    license_number: 'EIN-98-7654321',
    issuing_authority: 'IRS (Internal Revenue Service)',
    document_url: null,
    expiry_date: format(addDays(today, 365), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-ein'),
  },
  {
    id: 'grand-br-002',
    business_id: 'demo-grandview-002',
    requirement_id: 'demo-req-nyc-1',
    status: 'satisfied',
    license_number: 'DCWP-MFV-2024-901',
    issuing_authority: 'DCWP (NYC Dept. of Consumer & Worker Protection)',
    document_url: null,
    expiry_date: format(addDays(today, 240), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-1'),
  },
  {
    id: 'grand-br-003',
    business_id: 'demo-grandview-002',
    requirement_id: 'demo-req-nyc-2',
    status: 'satisfied',
    license_number: 'DOHMH-PERMIT-2024-551',
    issuing_authority: 'DOHMH (NYC Dept. of Health & Mental Hygiene)',
    document_url: null,
    expiry_date: format(addDays(today, 300), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-2'),
  },
  {
    id: 'grand-br-004',
    business_id: 'demo-grandview-002',
    requirement_id: 'demo-req-nyc-3',
    status: 'satisfied',
    license_number: 'NYC-DOHMH-FPC-11029',
    issuing_authority: 'DOHMH (NYC Dept. of Health & Mental Hygiene)',
    document_url: null,
    expiry_date: format(addDays(today, 210), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-3'),
  },
  {
    id: 'grand-br-005',
    business_id: 'demo-grandview-002',
    requirement_id: 'demo-req-nyc-4',
    status: 'satisfied',
    license_number: 'NYS-TAX-771029',
    issuing_authority: 'NY State Dept. of Taxation & Finance',
    document_url: null,
    expiry_date: format(addDays(today, 330), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-4'),
  },
  {
    id: 'grand-br-006',
    business_id: 'demo-grandview-002',
    requirement_id: 'demo-req-nyc-5',
    status: 'satisfied',
    license_number: 'ECB-CLEAR-2024-001',
    issuing_authority: 'NYC ECB / OATH',
    document_url: null,
    expiry_date: format(addDays(today, 180), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-5'),
  },
  {
    id: 'grand-br-007',
    business_id: 'demo-grandview-002',
    requirement_id: 'demo-req-nyc-6',
    status: 'satisfied',
    license_number: 'COMMISSARY-AGREE-2024',
    issuing_authority: 'DOHMH Requirement',
    document_url: null,
    expiry_date: format(addDays(today, 270), 'yyyy-MM-dd'),
    extracted_via_ocr: false,
    requirement: DEMO_REQUIREMENTS.find(r => r.id === 'demo-req-nyc-6'),
  },
];

export const DEMO_PROFILES = [
  {
    id: 'rico',
    label: "Rico's Curbside Kitchen",
    subtitle: 'NYC Food Truck — Incomplete / 4 Status Types',
    business: DEMO_BUSINESS_RICO,
    requirements: DEMO_BUSINESS_REQUIREMENTS_RICO,
  },
  {
    id: 'grandview',
    label: 'Grandview Grill Co.',
    subtitle: 'NYC Food Truck — High Compliance (Ready for LA Demo)',
    business: DEMO_BUSINESS_GRANDVIEW,
    requirements: DEMO_BUSINESS_REQUIREMENTS_GRANDVIEW,
  },
  {
    id: 'mumbai',
    label: 'Spice Garden Restaurant',
    subtitle: 'Mumbai Restaurant Sample',
    business: DEMO_BUSINESS,
    requirements: DEMO_BUSINESS_REQUIREMENTS,
  },
];

